import { writeFile, mkdir } from 'node:fs/promises';
import { icon, paths } from '../public/assets/js/ui.js';

// Vite replaces this base in the build; source pages always work at localhost.
const siteBase = '/';

const nav = `<a class="skip-link" href="#swup" data-no-swup>Pular para o conteúdo</a>
<header class="navbar"><div class="nav-inner"><a class="brand" href="${paths.home}" aria-label="Noética — início"><img src="IMG/LogoSemnome.png" width="42" height="42" alt=""><span>noética<span class="brand-period">.</span></span></a>
<nav id="main-nav" class="nav-links" aria-label="Navegação principal"><a href="${paths.courses}">Trilhas</a><a href="${paths.inspirations}">Inspirações</a><a href="${paths.prompts}">Prompts</a><a href="${paths.community}">Comunidade</a></nav>
<div class="nav-actions"><a class="nav-account" href="${paths.login}" data-account-link>Entrar</a><a class="button button-small" href="${paths.dashboard}">Meu espaço ${icon('external')}</a><button class="icon-button menu-toggle" aria-label="Abrir menu" aria-controls="main-nav" aria-expanded="false">${icon('menu')}</button></div></div></header>`;

const footer = `<footer class="site-footer"><div class="container footer-top"><a class="brand" href="${paths.home}"><img src="IMG/LogoSemnome.png" width="36" height="36" alt=""><span>noética<span class="brand-period">.</span></span></a><p>Entenda o básico. Crie o próximo.</p><a href="${paths.courses}">Comece a aprender ${icon('arrow')}</a></div><div class="container footer-bottom"><span>© 2026 Noética · Feito para mentes curiosas.</span><button class="text-button" data-privacy>Seus dados e privacidade</button><button class="text-button" data-motion aria-pressed="false">Pausar animações</button></div></footer>`;

const home = `<section class="hero container">
<div class="hero-copy"><div class="eyebrow gsap-hero"><span class="status-dot"></span> SUA PRÓXIMA IDEIA COMEÇA AQUI</div><h1 class="gsap-hero">Você tem a ideia.<br>A gente abre<br><span>as possibilidades.</span></h1><p class="hero-description gsap-hero">Aprenda o básico da programação e transforme ideias em projetos com IA. Um passo de cada vez, do primeiro prompt ao seu próprio código.</p><div class="button-row gsap-hero"><a class="button" href="${paths.classroom}?aula=mentalidade">Começar minha jornada ${icon('arrow')}</a><a class="button button-ghost" href="${paths.inspirations}">Encontrar inspiração ${icon('external')}</a></div><div class="hero-footnote gsap-hero"><span>${icon('check')} Sem experiência prévia</span><span>${icon('check')} Aprenda no seu ritmo</span></div></div>
<div class="hero-art gsap-hero-img" aria-hidden="true"><div class="art-grid"></div><div class="orbit-ring ring-one"></div><div class="orbit-ring ring-two"></div><div class="art-label label-top"><span class="status-dot"></span> IDEIAS EM MOVIMENTO</div><img class="hero-symbol" src="IMG/LogoSemnome.png" width="580" height="580" alt=""><div class="floating-code"><div class="window-dots"><i></i><i></i><i></i><span>primeiro-passo.js</span></div><code><span class="code-purple">const</span> ideia = <span class="code-gold">"e se eu criasse?"</span>;<br><span class="code-purple">const</span> possibilidades = <span class="code-gold">Infinity</span>;<br><span class="code-muted">// o próximo passo é seu.</span></code></div><span class="art-coordinate">23° 33′ S &nbsp; / &nbsp; SEM LIMITES PARA CRIAR</span></div>
</section>
<div class="learning-strip"><div class="container"><span>O FUTURO SE APRENDE FAZENDO</span><span>HTML & CSS</span><i>✳</i><span>JavaScript</span><i>✳</i><span>Inteligência artificial</span><i>✳</i><span>Suas ideias</span></div></div>
<section class="section container" id="sobre"><div class="section-heading gsap-scroll"><div><p class="eyebrow">O MÉTODO NOÉTICA</p><h2>Aprender. Experimentar.<br><span class="muted">Criar algo seu.</span></h2></div><p>IA como parceira. Curiosidade como ponto de partida. Entendimento para você seguir com autonomia.</p></div><div class="method-grid"><article class="method-card gsap-scroll"><span class="step">01 / ENTENDA</span>${icon('book')}<h3>Uma base que fica.</h3><p>Conceitos claros, exemplos pequenos e espaço para perguntar. Entenda o que o código faz antes de dar o próximo passo.</p></article><article class="method-card gsap-scroll"><span class="step">02 / EXPERIMENTE</span>${icon('spark')}<h3>Pense junto com a IA.</h3><p>Aprenda a pedir, revisar e melhorar. Transforme uma conversa em uma solução que você consegue explicar.</p></article><article class="method-card gsap-scroll"><span class="step">03 / CONSTRUA</span>${icon('rocket')}<h3>Da ideia à primeira versão.</h3><p>Exercícios, briefings e projetos para sair do tutorial e construir um portfólio com a sua perspectiva.</p></article></div></section>
<section class="section section-tinted"><div class="container"><div class="section-heading gsap-scroll"><div><p class="eyebrow">UM CAMINHO POSSÍVEL</p><h2>Seu primeiro “eu fiz isso”.</h2></div><a class="text-link" href="${paths.courses}">Conhecer as trilhas ${icon('arrow')}</a></div><div class="home-tracks"><a class="home-track gsap-scroll" href="${paths.classroom}?aula=mentalidade"><span>01</span><div><h3>Fundamentos da programação</h3><p>HTML, CSS, JavaScript e os primeiros porquês.</p></div><small>4 aulas</small>${icon('arrow')}</a><a class="home-track gsap-scroll" href="${paths.classroom}?aula=briefing"><span>02</span><div><h3>IA como parceira de código</h3><p>Prompts, revisão e uma boa dose de pensamento crítico.</p></div><small>4 aulas</small>${icon('arrow')}</a><a class="home-track gsap-scroll" href="${paths.classroom}?aula=dados"><span>03</span><div><h3>Seu primeiro projeto</h3><p>Do dado salvo à versão pronta para compartilhar.</p></div><small>4 aulas</small>${icon('arrow')}</a></div></div></section>
<section class="section container"><div class="start-banner gsap-scroll"><div><p class="eyebrow">NÃO PRECISA SABER TUDO PARA COMEÇAR</p><h2>Só precisa dar<br>o primeiro passo.</h2><p>As aulas estão abertas. Sua curiosidade também?</p></div><a class="button" href="${paths.classroom}?aula=mentalidade">Vamos criar algo ${icon('arrow')}</a><span class="banner-symbol" aria-hidden="true">✳</span></div></section>`;

const definitions = [
  ['home', 'index.html', 'Noética | Aprenda programação com IA', 'Aprenda programação do básico ao primeiro projeto, com IA, exercícios e inspirações. Comece sem experiência prévia.', home],
  ['courses', 'public/pages/cursos.html', 'Trilhas de aprendizagem | Noética', 'Três trilhas abertas para aprender fundamentos, usar IA e construir seu primeiro projeto.', '<div class="container page-container"><header class="page-heading"><p class="eyebrow gsap-hero">APRENDA NO SEU RITMO</p><h1 class="gsap-hero">Todo começo tem<br><span>um caminho.</span></h1><p class="gsap-hero">Três trilhas que se conectam. Comece do zero ou escolha o próximo passo da sua jornada.</p></header><div id="courses-content"></div></div>'],
  ['classroom', 'public/pages/classroom.html', 'Sala de aula | Noética', 'Leia, pratique no laboratório e acompanhe seu progresso em programação.', '<div class="container classroom-container" id="classroom-content"><p class="loading-message">Preparando sua aula…</p></div>'],
  ['dashboard', 'public/pages/dashboard.html', 'Meu espaço | Noética', 'Seu progresso, anotações e projetos em um só lugar.', '<div class="container page-container" id="dashboard-content"><p class="loading-message">Preparando seu espaço…</p></div>'],
  ['inspirations', 'public/pages/inspiracoes.html', 'Inspirações para criar | Noética', 'Explore seis ideias de projetos com briefings, critérios e sugestões de estudo.', '<div class="container page-container"><header class="page-heading"><p class="eyebrow gsap-hero">UM PONTO DE PARTIDA, INFINITAS VERSÕES</p><h1 class="gsap-hero">Ideias que acendem<br><span>outras ideias.</span></h1><p class="gsap-hero">Explore, adapte e dê o seu toque. Cada conceito vem com um briefing para você começar a construir.</p></header><div id="inspirations-content"></div></div>'],
  ['prompts', 'public/pages/prompts.html', 'Biblioteca de prompts | Noética', 'Prompts para planejar, construir, revisar e entender código com IA.', '<div class="container page-container"><header class="page-heading"><p class="eyebrow gsap-hero">MENOS TELA EM BRANCO. MAIS DIREÇÃO.</p><h1 class="gsap-hero">Boas perguntas.<br><span>Novas possibilidades.</span></h1><p class="gsap-hero">Um ponto de partida para conversar com a IA. Copie, acrescente contexto e aprenda com a resposta.</p></header><div id="prompts-content"></div></div>'],
  ['community', 'public/pages/comunidade.html', 'Comunidade e dúvidas | Noética', 'Encontre respostas para começar e compartilhe dúvidas com outros estudantes.', '<div class="container page-container"><header class="page-heading"><p class="eyebrow gsap-hero">APRENDER TAMBÉM É TROCAR</p><h1 class="gsap-hero">Toda pergunta<br><span>abre uma porta.</span></h1><p class="gsap-hero">Encontre uma direção para sua dúvida e compartilhe o que você está aprendendo.</p></header><div id="community-content"></div></div>'],
  ['login', 'public/pages/login.html', 'Sua conta | Noética', 'Entre para sincronizar seu progresso ou continue aprendendo sem cadastro.', '<div class="container auth-container" id="auth-content"><p class="loading-message">Preparando sua conta…</p></div>'],
  ['admin', 'public/pages/admin-seed.html', 'Conteúdo da escola | Noética', 'Informações sobre o conteúdo das aulas.', '<section class="container page-container narrow"><p class="eyebrow">CONTEÚDO DA ESCOLA</p><h1>O conhecimento já está aqui.</h1><p class="lead">As aulas agora fazem parte do projeto e estão disponíveis desde o primeiro acesso. Não é necessário preencher o banco de dados para começar.</p><a class="button" href="public/pages/cursos.html">Explorar as trilhas</a></section>'],
];

for (const [page, file, title, description, body] of definitions) {
  await mkdir(file.includes('/') ? file.slice(0, file.lastIndexOf('/')) : '.', { recursive: true });
  await writeFile(file, `<!doctype html>\n<html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="description" content="${description}"><meta name="theme-color" content="#0a0a0c"><base href="${siteBase}"><title>${title}</title><link rel="icon" type="image/png" href="/IMG/LogoSemnome.png"><link rel="stylesheet" href="/public/assets/css/style.css"><script type="module" src="/public/assets/js/main.js"></script></head><body>${nav}<main id="swup" class="transition-fade" data-page="${page}" tabindex="-1">${body}</main>${footer}<dialog id="app-dialog" aria-labelledby="dialog-title"></dialog><div id="toast" role="status" aria-live="polite" hidden></div><noscript><div class="no-script">Ative o JavaScript para usar as aulas, exercícios e seu espaço de estudo.</div></noscript></body></html>\n`, 'utf8');
}
console.log(`${definitions.length} páginas geradas.`);
